[project]
name = "7circles"
description = "The Seven Circles Theorem made with manim"
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
# render with -qk for final video
render-introduction = "manim -qp -a introduction.py"
render-main-result = "manim -qp -a main_result.py && ./ffmpeg_concat/concat_main_result.sh"
render-benedikt = "manim -qp -a animation.py"
render-paulina = "manim -qp -a paulinas_scenes.py"
render-horodisks = "manim -qp -a horodisks.py"

render-all = {depends_on = [
    "render-introduction",
    "render-main-result",
    "render-benedikt",
    "render-paulina",
    "render-horodisks",
    "concat-scenes"
]}

[dependencies]
manim = ">=0.17.0,<0.18"
ffmpeg = ">=5.1.2,<5.2"
tectonic = ">=0.15.0,<0.16"
