name: Render videos
on: push
jobs:
  main_result:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes (Main Result)
        uses: pavelzw/manim_community_renderer@v2
        id: renderer
        with:
          source_file: main_result.py
          pre_render: tlmgr install mathtools
          # concat all scenes into one video file
          post_render: sh ./ffmpeg_concat/concat_main_result.sh
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: main_result
          path: ${{ steps.renderer.outputs.video_path }}
          retention-days: 5
  benedikt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes (Benedikt)
        uses: pavelzw/manim_community_renderer@v2
        id: renderer
        with:
          source_file: animation.py
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: benedikt
          path: ${{ steps.renderer.outputs.video_path }}
  paulina:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes (Paulina)
        uses: pavelzw/manim_community_renderer@v2
        id: renderer
        with:
          source_file: paulinas_scenes.py
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: paulina
          path: ${{ steps.renderer.outputs.video_path }}
  horodisks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes (Horodisks)
        uses: pavelzw/manim_community_renderer@v2
        id: renderer
        with:
          source_file: horodisks.py
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: horodisks
          path: ${{ steps.renderer.outputs.video_path }}