name: Render videos
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Rendering Scenes (Main Result)
        uses: pavelzw/manim_community_renderer@master
        id: renderer
        with:
          source_file: main_result.py
          args: "-qk"
      - name: Save output as artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Videos
          path: ${{ steps.renderer.outputs.video_path }}